services:
  - type: web
    name: insta-downloader
    env: node
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y ffmpeg python3 python3-pip
      pip3 install yt-dlp
      npm install
    startCommand: node server.js
